name: Subscribers Update

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get Subscribers Update
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        python3 subscribers.py

    - name: Save Update
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "github-actions[bot]"

        git add subscribers_updates.json

        git commit -m "Save Update"

    - name: Push Update
      uses: ad-m/github-push-action@master
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}